#include <vector>
#include <iostream>
#include "../include/customer.h"
#include <stdlib.h>
#include <ctime>
#include <random>

customer::customer()
{
    customer::customerName();
    std::random_device dev;
    std::mt19937 rng(dev());
    std::uniform_int_distribution<std::mt19937::result_type> dist2(2, 6);
    TimeTaken = dist2(rng);
}

void customer::customerName()
{
    std::vector<std::string> names{"Ace",
                                   "Alaska",
                                   "Alexander",
                                   "Alfalfa",
                                   "Alfie",
                                   "Appollo",
                                   "Archie",
                                   "Arnold",
                                   "Asterix",
                                   "Audi",
                                   "Auggie",
                                   "Bagel",
                                   "Baloo",
                                   "Bam Bam",
                                   "Bandit",
                                   "Barcode",
                                   "Barney",
                                   "Bear",
                                   "Benjamin",
                                   "Benji",
                                   "Benny",
                                   "Bilbo",
                                   "Billy",
                                   "Black Beard",
                                   "Blackie",
                                   "Blackjack",
                                   "Blaze",
                                   "Bob",
                                   "Boston",
                                   "Breeze",
                                   "Bruce",
                                   "Bruno",
                                   "Buddy",
                                   "Bugs Bunny",
                                   "Bugster",
                                   "Bugsy",
                                   "Bun Bun",
                                   "Buster",
                                   "Butters",
                                   "Cadbury",
                                   "Caesar",
                                   "Caramel",
                                   "Carter",
                                   "Charlie",
                                   "Chesswood",
                                   "Chester",
                                   "Chewbacca",
                                   "Chip",
                                   "Chomper",
                                   "Chubby",
                                   "Claude",
                                   "Cloudy",
                                   "Cole",
                                   "Comet",
                                   "Cookie",
                                   "Cooper",
                                   "Copper",
                                   "Cosby",
                                   "Cotton Puff",
                                   "Dallas",
                                   "Dalton",
                                   "Dante",
                                   "Darryl",
                                   "Delboy",
                                   "Delta",
                                   "Denzel",
                                   "Dexter",
                                   "Dobby",
                                   "Domino",
                                   "Donald",
                                   "Draco",
                                   "Dumbo",
                                   "Duncan",
                                   "Dusty",
                                   "Echo",
                                   "Einstein",
                                   "Elvis",
                                   "Emerson",
                                   "Emmitt",
                                   "Fabio",
                                   "Fitch",
                                   "Floppy",
                                   "Flopsy",
                                   "Flumpy",
                                   "Forrest",
                                   "Fred",
                                   "Freddie",
                                   "Frodo",
                                   "Gadget",
                                   "Galaxy",
                                   "George",
                                   "Gizmo",
                                   "Goblin",
                                   "Goober",
                                   "Goofy",
                                   "Guinness",
                                   "Gus",
                                   "Hal",
                                   "Harry",
                                   "Harvey",
                                   "Henry",
                                   "Herbie",
                                   "Hermie",
                                   "Hip Hop",
                                   "Homer",
                                   "Hondo",
                                   "Honey",
                                   "Honey Bunny",
                                   "Hopper",
                                   "Hopscotch",
                                   "Houdini",
                                   "Huck",
                                   "Hudini",
                                   "Hugo",
                                   "Humphrey",
                                   "Iggy",
                                   "Jack",
                                   "Jackie",
                                   "Jake",
                                   "Jasper",
                                   "Jazz",
                                   "Jelly Bean",
                                   "Jesaja",
                                   "Jesse",
                                   "Jet",
                                   "Joey",
                                   "Jonas",
                                   "Karl",
                                   "Kirby",
                                   "Knight",
                                   "Kobie",
                                   "Kodo",
                                   "Lenny",
                                   "Leo",
                                   "Leopold",
                                   "Lone Ranger",
                                   "Lunn",
                                   "Majestic",
                                   "Marble",
                                   "Max",
                                   "Maxwell",
                                   "Merlin",
                                   "Midnight",
                                   "Milly",
                                   "Milo",
                                   "Momo",
                                   "Moody",
                                   "Moose",
                                   "Mr. Fuzzlebuns",
                                   "Murphy",
                                   "Mystic",
                                   "Nacho",
                                   "Nemo",
                                   "Nero",
                                   "Ninja",
                                   "Noel",
                                   "Noodle",
                                   "Nova",
                                   "Obelix",
                                   "Octha",
                                   "Oliver",
                                   "Ollie",
                                   "Oreo",
                                   "Oscar",
                                   "Pancake",
                                   "Patch",
                                   "Peanut",
                                   "Pepper",
                                   "Pepsi",
                                   "Peter",
                                   "Phantom",
                                   "Pillsbury",
                                   "Pippin",
                                   "Pluto",
                                   "Porter",
                                   "Porthos",
                                   "Prancer",
                                   "Prince",
                                   "Prince George",
                                   "Random",
                                   "Rascal",
                                   "Raven",
                                   "Reginald",
                                   "Rex",
                                   "Riley",
                                   "River",
                                   "Rocket",
                                   "Rocky",
                                   "Roger Rabbit",
                                   "Rolf",
                                   "Romeo",
                                   "Rosco",
                                   "Ross",
                                   "Rowdy",
                                   "Rufus",
                                   "Sage",
                                   "Sammy",
                                   "Scooter",
                                   "Scotch",
                                   "Scout",
                                   "Scruffy",
                                   "Shadow",
                                   "Shippy",
                                   "Simba",
                                   "Skippe",
                                   "Smithers",
                                   "Smokey",
                                   "Snoop",
                                   "Snoopy",
                                   "Snowball",
                                   "Snowman",
                                   "Soldier",
                                   "Solomon",
                                   "Spanky",
                                   "Spencer",
                                   "Spike",
                                   "Spirit",
                                   "Spooky",
                                   "Spot",
                                   "Stanley",
                                   "Stewart Little",
                                   "Stewie",
                                   "Stoker",
                                   "Stormy",
                                   "Stuart",
                                   "Sylvester",
                                   "Tarzan",
                                   "Teddy",
                                   "Tequila",
                                   "Tex",
                                   "Theodore",
                                   "Thor",
                                   "Thumper",
                                   "Tidbit",
                                   "Tigger",
                                   "Tinkerbell",
                                   "Toby",
                                   "Tornado",
                                   "Trumpet",
                                   "Turbo",
                                   "Uncle Buck",
                                   "Waldo",
                                   "Winston",
                                   "Wolfgang",
                                   "Wonka",
                                   "Yoda",
                                   "Yogi",
                                   "Zero",
                                   "Ziggy",
                                   "Zorro"};
    std::random_device dev;
    std::mt19937 rng(dev());
    std::uniform_int_distribution<std::mt19937::result_type> dist2(0, names.size() - 1);
    int randomNumber = dist2(rng);
    name = names.at(randomNumber);
}